version: '3'
services:
  app:
    image: centurylink/drupal
    links:
      - db
    ports:
      - 80
    restart: always
  db:
    image: mysql
    ports:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
      MYSQL_DATABASE: drupal
    restart: always
